services:
  backend:
    build: ./backend
    image: ${DOCKERHUB_USERNAME}/stack-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    image: ${DOCKERHUB_USERNAME}/stack-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
