name: Full Stack CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend
      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Test Backend
        run: |
          cd backend
          npm test

      # Frontend
      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/testing-mern

            echo "Pulling latest code..."
            git pull origin main

            echo "Updating backend..."
            cd backend
            npm install

            echo "Restarting backend..."
            pm2 restart backend || pm2 start src/index.js --name backend

            echo "Updating frontend..."
            cd ../frontend
            npm install
            npm run build

            echo "copy the build files to nginx directory..."
            sudo cp -r ~/testing-mern/frontend/build/* /var/www/html/

            echo "restarting nginx..."
            sudo systemctl restart nginx

            echo "Deployment completed!"